---
version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "%(asctime)s %(levelname)s [%(filename)s:%(lineno)s]: %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
    console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout

    info_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO #In the file, only logs with this level will appear
        formatter: simple
        filename: info.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR #In the file, only logs with this level will appear
        formatter: simple
        filename: errors.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    error_logger:
        level: ERROR
        handlers: [console]
        propagate: no
    mixed_debug_logger: #to call this logger: `log = logging.getLogger('mixed_debug_logger')`
        level: DEBUG
        handlers: [console, info_file_handler, error_file_handler]
    mixed_info_logger:
        level: INFO
        handlers: [console, info_file_handler, error_file_handler]

#root:
#    level: INFO #Change this to set the general log level
#    handlers: [console, info_file_handler, error_file_handler]


